version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.23
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: droneFeederDb
      MYSQL_ROOT_PASSWORD: pass
