version: "3.8"

services:
  db:
    container_name: drone_feeder_db
    image: mysql:8.0.23
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: droneFeederDb
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
